### ISSUE TITLE
Is it a "Good" or a "Bad" roll?

### ISSUE THREAD

**Issue by aloisdg** [DnDGen/RollGen#11]
Hello,

It is more about `Succeed` or `Failed` roll, but I like to think that every roll has an alignment :wink: 

I can be help a DM to know how to describe the output of a roll. With long, complicated, rool it can be difficult to adjust the tone of the roleplay to follow the roll.

Basically, I see this as `enum`:

``` C#
enum RollType {
        CriticalSuccess,
        GreatSuccess,
        Success,
        Standard, // or Medium or Normal as name, I don't know for this one
        Fail,
        GreatFail,
        CriticalFail
}
```

The method to determine the type of a roll could be a simple average between the minimum value possible and the best value possible.

Another solution could be to use the World of Darkness's system, Each crit from one side, remove a crit from the other side.

If this feature is accepted, I would love to try to implement it myself.

Cheers,

**Comment by cidthecoatrack** [comment]
This is intriguing - it could be very interesting.  It would complicate the roll - it means you would have to either return a complex object with a `value` and `quality` (or something like that).  Or, you would need a method that takes in the original roll and the rolled value, returning the quality.

As for the `Standard` conundrum, I would go with `Average` - saying "an average roll" makes a certain sort of sense.

This method would not be quick, since it would require many iterations over the given roll in order to determine what the average range is.

If you want to take a crack at it, I would be more than happy to look at the pull request. :)  I will give you a heads up that before I approve a pull request, I am going to look for a couple things:
1. Tests.  I expect there to be automated tests with 100% coverage of the new features you add.
2. Clean code (as described by Uncle Bob, or Robert C. Martin).  This is a coding style.  The current code reflects this style.  If you have questions, I will happily discuss it with you.  It will probably be easiest to do this via code reviews once you have made the pull request.

If you go and look at #6 , you can see how a pull request tends to go - a lot of good back-and-forth discussion. :)

**Comment by aloisdg** [comment]
> Or, you would need a method that takes in the original roll and the rolled value, returning the quality.

I was thinking about this. We wont break any compatibility and I prefer to use one function for one thing. Also, we could create a method who will call both and return an object.

> As for the Standard conundrum, I would go with Average - saying "an average roll" makes a certain sort of sense.

Agree for `Average`.

> If you go and look at #6 , you can see how a pull request tends to go - a lot of good back-and-forth discussion.

Indeed :smile: I don't plan to do it right now by the way. If you have a need for this feature, feel free to implement it.

**Comment by cidthecoatrack** [comment]
No immediate need. Take your time :)

**Comment by cidthecoatrack** [comment]
Also don't worry about returning and object with both. Just have the two methods.

**Comment by LiruMouse** [comment]
If I may suggest something, you could have it work something like:

``` cs
IEnumerable<int> GetIndividualRolls(string roll, ref long cumulative_total)
{
    int dice = /*blah*/;
    int quantity = /*blah*/;
    // Perhaps null check cumulative_total so when this feature isn't being used, we don't waste time here.
    cumulative_quantity += quantity*dice;
    // return blahblah
}
```

Some things to consider for this are how modifiers like +/-5 should affect it, and how natural `die max` should factor into massive dice expressions with different `die max`s (surely a natural 1 on a d20 shouldn't negate a natural 100 on a d100), though...
