### ISSUE TITLE
Computing dice expressions into single numbers within strings

### ISSUE THREAD

**Issue by LiruMouse** [DnDGen/RollGen#13]
Related to #10, it'd be nice to be able to do something like
`The druid attacks with his Flame Blade, dealing 1d8 +min(4/2, 10) damage.`
Where 4 would be the level (which we could have replaced inside of the program that would send this string to RollGen).
And we could get back output like:
`The druid attacks with his Flame Blade, dealing 9 damage.`

**Comment by cidthecoatrack** [comment]
I'm not entirely sure what the `+min(4/2, 10)` is supposed to mean.  Could you elaborate?

**Comment by LiruMouse** [comment]
min and max are functions (they work with albatross), passed numbers they give the lowest and highest respectively, (I'm in a DnD session right now, future replies may be delayed)

**Comment by LiruMouse** [comment]
```
10:02 PM Liru said: !roll 1d8+min(4/2, 10)
10:02 PM 🎵Electra🎵 said: 
(7)+min(4/2, 10) = 9.
```

**Comment by cidthecoatrack** [comment]
Ah, I see.  Well, unfortunately I have not found a "is valid expression" method within Albatross, so we would have to hand-roll something that would be able to detect those things.  If you want, you can take a stab at it in a pull request when you have the time.

**Comment by LiruMouse** [comment]
I was thinking we could do as I had suggested in #10, putting expressions to be evaluated in some sorta wrapper characters, and just let the evaluator complain how it normally would if the expressions don't compute.

**Comment by cidthecoatrack** [comment]
That's easy enough for the expression - but considering that we have regex that can accurately find expressions doing simple arithmetic and die rolls, I would think that the syntactic sugar we would add for basically be if we wanted to use more complex Albatross features.  So, if you gave the dice `1d6*1000`, it would still evaluate - but if you want to evaluate `1d8+min(4/2, 10)`, then you might need to wrap it, as you suggest, so it might be something like `{1d8+min(4/2, 10)}` - or however we decide to wrap it.  But we definitely still also want to preserve the ability that we have right now of plain text transformations - in other words, after this change is done, I should not have to go to old strings that compute correctly now and add the syntactic sugar.

**Comment by LiruMouse** [comment]
Indeed, that is the plan! Just have to put it into code from the design
plan in my head one of these days.

**Comment by cidthecoatrack** [comment]
Awesomesauce.  Looking forward to seeing that  pull request :)

**Comment by LiruMouse** [comment]
I am going to use the old regex, from before #10 in this feature, because anything within the dice expression should be valid, since the fix #15 won't be able to pick up functions like min and max and any other functions that the parser supports.

**Comment by cidthecoatrack** [comment]
Just keep in mind that the old regex fails on some pretty simple string-literal examples.  Without some sort of pre-`d` check, you might get the oddity of `1d3 Hill giants and 2d4 orcs` parsing out as `(1d3) Hill giants an(d 2)(d4) orcs`, which is obviously not right.  And because this is such a simple case, I don't think requiring syntax sugar to parse it is a good option, because that will basically mean that all rolls need to be wrapped in syntax if it's not a pure expression passed in.

For some of the higher-up generator projects, requiring that syntax will be a breaking change.  I would like to avoid it if at all possible - but if not, then we might just have to bite the bullet.

**Comment by cidthecoatrack** [comment]
Having said that last comment, if your plan is to use the old regex _within_ the syntactic sugar, then that will work fine. :)

**Comment by LiruMouse** [comment]
Yeah, the plan is to use the old only within the sugar.

**Comment by cidthecoatrack** [comment]
Awesome, that makes total sense. :)  I am also beginning to wonder if there would be a benefit in some sort of `IsValidExpression` method.  At the easiest (albeit not most efficient) form, it would take in a string, try to compute it within a try-catch, and if it threw an exception, return false.  Otherwise, true.  This would definitely be a separate feature than what you are doing here - but I feel it would be useful in tandem with some of these other features (such as verifying that what is in the syntactic sugar is a valid expression).  Just a thought.

**Comment by LiruMouse** [comment]
Such a function wouldn't be needed for this, right, but for others perhaps. I wonder if Albatross returns a container of all qualified symbol strings, we could take this and do `$"({string.Join("|", container)})"`... no... that wouldn't work when something is wrapped in parentheses because it's a function... or would it... we'll have to see if there is such a thing.

**Comment by cidthecoatrack** [comment]
That would be handy.  From my own exploration, Albatross's documentation is pretty minimal.

I should state that I am by no means wed to Albatross - if we find a different expression evaluator that will work better, then I am all for it. :)

**Comment by LiruMouse** [comment]
Is Albatross existent in opensource somewhere?

**Comment by cidthecoatrack** [comment]
It's a Nuget package.  Here is ts GitHub page: https://github.com/RushuiGuan/expression/
