### ISSUE TITLE
Let string rolls be used anywhere

### ISSUE THREAD

**Issue by cidthecoatrack** [DnDGen/RollGen#30]
Let `string` input (such as `4d6k3`) be used anywhere a number can be passed.  For instance, `dice.Roll("3d7").d("4d6k3").Keeping("1d3").AsSum()` or `dice.Roll().d("2d3")`.  This will necessitate moving code in `RandomDice` that parses these to be moved to its own class.

**Comment by cidthecoatrack** [comment]
This will block on #28

**Comment by cidthecoatrack** [comment]
This further blocks on the ability for expressions to be assessed with parantheses.

Albatross knows how to assess them, but our regex to detect them does not, which makes replacement in phrases, as well as `(1)d(2)k(3)` impossible to do.  Once that regex is figured out, this can go forward.

**Comment by LiruMouse** [comment]
> 
> 
> This further blocks on the ability for expressions to be assessed with parantheses.
> 
> Albatross knows how to assess them, but our regex to detect them does not, which makes replacement in phrases, as well as `(1)d(2)k(3)` impossible to do. Once that regex is figured out, this can go forward.

Unfortunately, C# regex does not have defined groups or any good recursion, so what I've put together for this is a loose detection for the expression inside the parentheses, but that shouldn't matter since we can just eval the inside until we're done.

So I'm gonna explain this, because it's gonna be rather complicated
`\d*\s*d\s*\d+(?:\s*(!|k\s*\d+))?`
This is a common dice expression, it means any numbers followed by any spaces followed by a d then any spaces then at least one numbers then maybe {any spaces then either {an exclamation mark OR {a k followed by any spaces followed by at least one numbers}}}

Now we have this expression, which will replace instances where we look for a number
`(\d|\([\d\sdk!()*\/+\-%^><=]+\))`
It means any number OR {an opening parenthesis followed by at least one of {a digit, a space, d, k, !, opening parenthesis or closing parenthesis, or an operator that albatross can use(if we want, we could allow math operators, digits, space, parentheses and A-Za-z so that albatross can be used to its full potential with strings like min and pi, see [here](https://github.com/RushuiGuan/expression/tree/master/src/Albatross.Expression/Operations))} followed by a closing parenthesis}
I know this seems wrong, and it is, but once we get into the inner evaluation, we'll find that out, so this kinda loose detection is okay!
If we  do want to do as I suggested above, with albatross string operators allowed in parentheses, we would need to do a little more, does albatross have a way to collect all its potential operator string names? Because  we could then join such a container together as a string using `|`, and test for that along with the other operations where numbers belong.

So our dice expression now becomes
`(\d|\([\d\sdk!()*\/+\-%^><=]+\))*\s*d\s*(\d|\([\d\sdk!()*\/+\-%^><=]+\))+(?:\s*(!|k\s*(\d|\([\d\sdk!()*\/+\-%^><=]+\))+))?`

So we now have three main capture groups, we could name them with `?'name'` if wanted to, but I think we're fine addressing them by number.

For evaluating our captures from inside the parentheses, we may want to use  \A at the beginning and \z at the end wrapped around the same expression we used to find them, I'm unsure if this matters though, for performance.

**Comment by LiruMouse** [comment]
Oh, and in order to make that C#-ready, every \ needs to be doubled.

**Comment by cidthecoatrack** [comment]
Wow, that is some great regex work.  Let me dive in and see if we might be close to the mark on this one.  If so, this is a HUGE help!

**Comment by cidthecoatrack** [comment]
I actually figured out a non-regex way to handle it that worked really well.  I'll be merging it to develop soon and making another release!

**Comment by LiruMouse** [comment]
I don't believe this is closed yet? Only the subissue, not the string rolls everywhere thing has been done, no?

**Comment by cidthecoatrack** [comment]
The string rolls are done and done - they are accepted as quantities, die, and keeps.
