### ISSUE TITLE
Create ExpressionEvaluator

### ISSUE THREAD

**Issue by cidthecoatrack** [DnDGen/RollGen#7]
So that the `Random` dependency can be separately encapsulated from the `Albatross` dependency, there should be a separate ExpressionEvaluator that handles the expression evaluation/the Albatross code.  Logic around this was discussed (amongst other things) in #6

**Comment by LiruMouse** [comment]
This might have made it a little too complex to create a new DomainDice, might it be possible to create a class, perhaps in another library, that would make it easier for the user to create one?
Something like:

``` cs
var rd = new RandomDice(new Random());
```

instead of

``` cs
var dd = new DomainDice(new AlbatrossExpressionEvaluator(new Albatross.Expression.Parser()), new RandomPartialRollFactory(new Random()));
```

Just for ease of use of the library, I mean. Although, maybe it is easy enough to figure it out, I did... but I knew what was happening.

**Comment by cidthecoatrack** [comment]
Again, as explained in the README (although it needs to be updated), ideally you should be using Ninject to build these objects, because of this kind of complexity.  Is that a possibility for you, @Lirusaito ?

**Comment by LiruMouse** [comment]
I was using the second method, but it still works fine for me... actually, if the README was updated, there'd be no confusion.

**Comment by cidthecoatrack** [comment]
README has been updated - I just eliminated the manual option.  Of course, just as you did, people can go poking around and figure out how to build it on their own - but recommended to use the bootstrapper.
